### ISSUE TITLE
Suggestion: Interface to choose what doctranes you want

### ISSUE THREAD

**Issue by zephiowl** [Wheels35/CultoftheLamb#1]
Hey so i had a small idea; instead of manually editing the code of the save file i thing it would be a good idea to make some sort of interface either cli or gui etc. And basically have the program edit the text file for you; it would wipe any existing doctranes and you could manually select which ones you want to keep and have a small description about what each one of them do (Pulled from the game)

I think it'd help a lot and allow tons more accessibility when it comes to using your tool.

**Comment by Wheels35** [comment]
Hey, I appreciate the suggestion and was actually my first thought initially when I started going down the road of collecting the Doctrine Numbers.

Unfortunately, I realized quickly that it's not only the 'DoctrineUnlockedUpgrades' field but 'CultTraits' and 'UnlockedUpgrades' that get modified when unlocking Doctrines, so it's not as simple as wiping out the whole field and just selecting those you want to keep.

That being said, I am actively working on a gui to do this, but it's possible that someone else will come along first and finish one before I have the chance too. Or, it's possible they reverse course and allow people to change Doctrines.

**Comment by zephiowl** [comment]
Ahhh i see; I'm not to well versed with programming to be honest with you. Mostly just making small tools and meme program's none of them being gui. But it could be possible to have an array of indexed words and data, or just a match statement. (all the doc numbers names etc) And have the application filter line by line for a match. Then replace or remove the content. It could solve the issue of modification.

At least that's how i would probably go around doing it.

**Comment by Wheels35** [comment]
Yep, also was my thought, unfortunately they reuse numbers as well, so just searching for 110 pulls up multiple different options.
Currently the easiest way I can think of is pulling in the arrays and display them individually in a text box with no modifications, and allowing someone to edit it, it would still be manual, and it would essentially be nothing more than a glorified text editor.

Another option was for me to just pull in the sections, essentially making them 'blank' and requiring someone to add what they want. Possibly even displaying 'existing' array but making that non-editable.

**Comment by zephiowl** [comment]
Taking a look at my own file i can see a format. It's ```"<Datatype>":[<array data value>],```  A possible way might be to filter line by line until you get a match; then filter that line character by character. Once you hit a , that is not surrounded by a number and comes after the datatype your targeting you know you've reached the end of the array; then you could possible wipe that entire selection and put the users custom array instead. 

![image](https://user-images.githubusercontent.com/66909997/185279885-7cb4963d-62be-4440-8b2b-40664f3a5f1c.png)
Cultraits

![image](https://user-images.githubusercontent.com/66909997/185279929-c02dbaf1-c93c-495d-8bb9-5a75c98a59e6.png)
DoctrineUnlockedUpgrades

**Comment by Wheels35** [comment]
First half is sort of what I'm already doing in my initial edit tests.

Second half of that is what I was thinking actually, at least as a stop gap for me, or any one else, code a proper editor.

**Comment by Wheels35** [comment]
Now that it has been all mostly mapped out work has begun on a save editor by a couple different people.

**Comment by vesper8** [comment]
There's one more value that I think needs to be changed if you really want to be a perfectionist about it.

For example, I changed the Pit Fight to Wedding. I made both changes that you mention in your readme and it worked. However in my 'Doctrines' tab where it just shows which doctrines you've chosen.. there's an exclamation point that will not go away no matter what, I believe the exclamation point is referring to the Pit Fight doctrine which I hadn't yet "hovered" over, but now that it's marked as an X instead since I now have Wedding, I can't get this exclamation mark to go away.. it shows on the tab only but once you visit the tab none of the doctrines have that exclamation point.

**Comment by Wheels35** [comment]
> There's one more value that I think needs to be changed if you really want to be a perfectionist about it.
> 
> For example, I changed the Pit Fight to Wedding. I made both changes that you mention in your readme and it worked. However in my 'Doctrines' tab where it just shows which doctrines you've chosen.. there's an exclamation point that will not go away no matter what, I believe the exclamation point is referring to the Pit Fight doctrine which I hadn't yet "hovered" over, but now that it's marked as an X instead since I now have Wedding, I can't get this exclamation mark to go away.. it shows on the tab only but once you visit the tab none of the doctrines have that exclamation point.

This is listed under:
```
    "Alerts": {
        "Doctrine": {
            "_alerts": [
            ],
            "_singleAlerts": [],
            "Total": 
```

Emptying the **_alerts** array and the "**Total"** under **_singleAlerts** should remove it

**Comment by zephiowl** [comment]
> Now that it has been all mostly mapped out work has begun on a save editor by a couple different people.

Would you be able to point to a few of those repos? I haven't really found any save editors publicly so if you're aware of any please inform me

**Comment by Wheels35** [comment]
> > Now that it has been all mostly mapped out work has begun on a save editor by a couple different people.
> 
> Would you be able to point to a few of those repos? I haven't really found any save editors publicly so if you're aware of any please inform me

Unfortunately, the two I know of for sure are not publicly available, and I have only heard about one or two others.

I have slowed down my development of mine as my guides here on github, or [https://wheels35.github.io/CultoftheLamb/](https://wheels35.github.io/CultoftheLamb/) knock most of what is needed out.
