### ISSUE TITLE
My name

### ISSUE THREAD

**Issue by pentalex** [Wheels35/CultoftheLamb#2]
Hey! Cool project, a few tiny things:

my name is "Pentalex" (as in, penta - alex) not "Pentalax" as was written in your README.md
Can I link your project in my README.md as well? I think it's a useful resource to accompany with my site.

Thank you!

**Comment by Wheels35** [comment]
I am so sorry for that, I thought i copied it, but when I typed it up it was in a flurry.
Of course you can! I'm working on prettifying the actual pages, but i just wanted to get something up for those until I can get around to more
